services:
  bot:
    build: .
    env_file:
      - .env.docker
    depends_on:
      - "db"
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
volumes:
  dbdata: